language: php
matrix:
  include:
  - php: 7.2
  - php: 7.3
script:
- "./run_tests.sh;"
- if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then ./run_dicto.sh; fi
addons:
  apt:
    packages:
    - unzip
install:
- cd ./libs/composer && composer install && cd ../..
env:
  global:
   - secure: QPx4Z5rZrlwda2f5buAG8KKumPAoL8Pn7fGVLAkKMtDhOw7K3bp2icq06JzoCxjm8gwLRZUT1nFAPtL1ka7IZL8l+8TSXYW3Fp0Q6ktUqBxDPldIrE80T37t6rNK74wsUIhTCa+FzPbrK7b2IVhoJcoDLx0+3jfQ4wRB+rzgChG73mgtoll0PIKbgTNmO7kMl1Eu7GiecYwhdz3uzb6IThF1aQCz4+QHRp4A4Hk+IiCZ6sJirzwVJvsCNz2ipj4HDVBQ5VhH58e7kqbM3No005BXuo17lxbn15z0sH5ebRtLL/xtpvgjnUis7OXC9m5zqKplUsv2J+Q1XVTGDd3VusC0lQyAuo4NH0JQYV+hZE0thbUSBq7HfNTVVeHM69FG/taTs+wpijVyF0od/+FQoew5RWcSP55hGYwUNGQTg99oWnlBM3gffw1h3VCJTedftDQntuVIK0oQRUTU1eotwQIU8iCMzswMdyDLPc1BIGYU7vy9GIl9zU5VjqBn2hDsgLbXmAZVtXArVfML1RX7opSmNeQh/bNXrgvlWJylSk3LghloLLi1AM8MbkKZch0q58ufeTyWETjBHHdBdma2AQa+vHLYwiUYWJC/XnupFVICIgnCFnXos/NQJjGMFglmvigGTUNmQl+y3M7FkcIH4GUhQBBmzG9/3W2txL0KshA=
