language: php
matrix:
  include:
  - php: 7.2
  - php: 7.3
script:
- "./run_tests.sh;"
- if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then ./run_dicto.sh; fi
addons:
  apt:
    packages:
    - unzip
install:
- cd ./libs/composer && composer install && cd ../..
env:
  global:
  - secure: Va1aVGJ57kOHz0e1ZrW4ybcCHVGn8q+s1Fz04wTQHGFinW+gGj3HiiGupbKRCUepyddplaiuMkiJ9TeJ5A46YbYPqqZlK6fbcY2fIz4QETuNdLM7S9CnuoCfcUvFMkscd1ElaUGeJN4BGl3ISr6raIyFMUTaoqPqXQJHMpkF9sbKmLhC5Yph+TmpL6z6JuSHfWn079jMzjNpbzBHX1ea8uOq9xx97b94Vf6RUv68AdBzXUQ7VoOkaPjDjnywT1ZPJc+OXATl6CwY2j1Dw/2xqHRem4l0DmPP6pIQhp9yZbrkaKN1YAGxS6K5mBIbAXJB/oB+cz6vyXrN/FxS1LH6vTNaiimgMHIgNI12unAc4KDpnzRcRrf0RKa76ZwYRtQwKd5pY8W0j9SeTOkx+vwRNApKEygZX0gPQH7BmLKiGH9vfKYoHSDgeT725ulS9fjpAzL5/Wwu9X8VUdBdcqo1uFErWHiHpSuh8rdBb7tAyVK2THZpU6T4brp2MjT8vpowLb+Xnodh0EEalPKDyj8A4YsfYn41I5kJ+OW3jxmOkbCuX/KyQvBuNfEB1Uq34sFm5Y+69yA9V1yWi4DwQ+0FYbr1DG1BmOG8TyyOzmi/WFHHO8m8W2IBzcp7CNgwOqRMppAA95sw5tED3iJqT9HPz+KQqVg55g1HKM4YCi8dFQA=